# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:

  format_listener:
    rules:
      - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ] }
      - { path: ^/, prefer_extension: true, fallback_format: html, priorities: [ html ] }

  exception:
    enabled: true
    
  view:
    view_response_listener:  force
    formats:
      json: true

  

  
